version: '3.8'

services:
  llama-server:
    build:
      context: ./ml_backend
    ports:
      - "8080:8080"
    networks:
      - llm-net

  interface-server:
    build:
      context: ./interface
    ports:
      - "8501:8501"
    depends_on:
      - llama-server
    networks:
      - llm-net

networks:
  llm-net:
    driver: bridge
